name: android build test

on:
  push:
    branches:
      - develop
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      path: test/android
    defaults:
      run:
        working-directory: test/android

    steps:
      - uses: actions/checkout@v4.1.0
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-java@v3.13.0
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
        with:
          gradle-version: current
          gradle-home-cache-cleanup: true
            # build-root-directory: ${{env.path}}

      - name: TEST
        run: |
          ls

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle Build
        run: ./gradlew assembleDebug

      - name: Run unit test
        run: ./gradlew testDebug
